//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JLS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.10.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double UiScale {
            get {
                return ((double)(this["UiScale"]));
            }
            set {
                this["UiScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double PlaylistSplitterWidth {
            get {
                return ((double)(this["PlaylistSplitterWidth"]));
            }
            set {
                this["PlaylistSplitterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public double BrowserSplitterWidth {
            get {
                return ((double)(this["BrowserSplitterWidth"]));
            }
            set {
                this["BrowserSplitterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlaylistColumns {
            get {
                return ((string)(this["PlaylistColumns"]));
            }
            set {
                this["PlaylistColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BrowserColumns {
            get {
                return ((string)(this["BrowserColumns"]));
            }
            set {
                this["BrowserColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedDeviceName {
            get {
                return ((string)(this["SelectedDeviceName"]));
            }
            set {
                this["SelectedDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public string WaveformStyle {
            get {
                return ((string)(this["WaveformStyle"]));
            }
            set {
                this["WaveformStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Waveform")]
        public string ControlStyle {
            get {
                return ((string)(this["ControlStyle"]));
            }
            set {
                this["ControlStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsVuMeterVisible {
            get {
                return ((bool)(this["IsVuMeterVisible"]));
            }
            set {
                this["IsVuMeterVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public double WindowWidth {
            get {
                return ((double)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double WindowHeight {
            get {
                return ((double)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastBrowserPath {
            get {
                return ((string)(this["LastBrowserPath"]));
            }
            set {
                this["LastBrowserPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExpandedFoldersJson {
            get {
                return ((string)(this["ExpandedFoldersJson"]));
            }
            set {
                this["ExpandedFoldersJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double SavedVolume {
            get {
                return ((double)(this["SavedVolume"]));
            }
            set {
                this["SavedVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTrackPath {
            get {
                return ((string)(this["LastTrackPath"]));
            }
            set {
                this["LastTrackPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LastTrackPosition {
            get {
                return ((double)(this["LastTrackPosition"]));
            }
            set {
                this["LastTrackPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FileScrollPos {
            get {
                return ((double)(this["FileScrollPos"]));
            }
            set {
                this["FileScrollPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TreeScrollPos {
            get {
                return ((double)(this["TreeScrollPos"]));
            }
            set {
                this["TreeScrollPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PlaylistsListScrollPos {
            get {
                return ((double)(this["PlaylistsListScrollPos"]));
            }
            set {
                this["PlaylistsListScrollPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlaylistTracksScrollJson {
            get {
                return ((string)(this["PlaylistTracksScrollJson"]));
            }
            set {
                this["PlaylistTracksScrollJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedPlaylistName {
            get {
                return ((string)(this["LastSelectedPlaylistName"]));
            }
            set {
                this["LastSelectedPlaylistName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medium")]
        public string TreeSpacing {
            get {
                return ((string)(this["TreeSpacing"]));
            }
            set {
                this["TreeSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medium")]
        public string TreeFontSize {
            get {
                return ((string)(this["TreeFontSize"]));
            }
            set {
                this["TreeFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medium")]
        public string ListSpacing {
            get {
                return ((string)(this["ListSpacing"]));
            }
            set {
                this["ListSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medium")]
        public string ListFontSize {
            get {
                return ((string)(this["ListFontSize"]));
            }
            set {
                this["ListFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medium")]
        public string PlaylistListSpacing {
            get {
                return ((string)(this["PlaylistListSpacing"]));
            }
            set {
                this["PlaylistListSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Medium")]
        public string PlaylistListFontSize {
            get {
                return ((string)(this["PlaylistListFontSize"]));
            }
            set {
                this["PlaylistListFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classic")]
        public string NowPlayingControlStyle {
            get {
                return ((string)(this["NowPlayingControlStyle"]));
            }
            set {
                this["NowPlayingControlStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Solid")]
        public string NowPlayingWaveformStyle {
            get {
                return ((string)(this["NowPlayingWaveformStyle"]));
            }
            set {
                this["NowPlayingWaveformStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Explorer")]
        public string LastOpenedView {
            get {
                return ((string)(this["LastOpenedView"]));
            }
            set {
                this["LastOpenedView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beautiful")]
        public string LyricsStyle {
            get {
                return ((string)(this["LyricsStyle"]));
            }
            set {
                this["LyricsStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GlobalHotkeysEnabled {
            get {
                return ((bool)(this["GlobalHotkeysEnabled"]));
            }
            set {
                this["GlobalHotkeysEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HotkeysJson {
            get {
                return ((string)(this["HotkeysJson"]));
            }
            set {
                this["HotkeysJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGaplessPlaybackEnabled {
            get {
                return ((bool)(this["IsGaplessPlaybackEnabled"]));
            }
            set {
                this["IsGaplessPlaybackEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsOsdEnabled {
            get {
                return ((bool)(this["IsOsdEnabled"]));
            }
            set {
                this["IsOsdEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top-Left")]
        public string OsdPosition {
            get {
                return ((string)(this["OsdPosition"]));
            }
            set {
                this["OsdPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BrowserSortColumn {
            get {
                return ((string)(this["BrowserSortColumn"]));
            }
            set {
                this["BrowserSortColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrowserSortAscending {
            get {
                return ((bool)(this["BrowserSortAscending"]));
            }
            set {
                this["BrowserSortAscending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrowserSortActive {
            get {
                return ((bool)(this["BrowserSortActive"]));
            }
            set {
                this["BrowserSortActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFullscreenVisualizerEnabled {
            get {
                return ((bool)(this["IsFullscreenVisualizerEnabled"]));
            }
            set {
                this["IsFullscreenVisualizerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClassicBars")]
        public string VisualizerStyle {
            get {
                return ((string)(this["VisualizerStyle"]));
            }
            set {
                this["VisualizerStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsOverlayVisualizerEnabled {
            get {
                return ((bool)(this["IsOverlayVisualizerEnabled"]));
            }
            set {
                this["IsOverlayVisualizerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFpsLimited {
            get {
                return ((bool)(this["IsFpsLimited"]));
            }
            set {
                this["IsFpsLimited"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TargetFps {
            get {
                return ((int)(this["TargetFps"]));
            }
            set {
                this["TargetFps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PlaybackMode {
            get {
                return ((string)(this["PlaybackMode"]));
            }
            set {
                this["PlaybackMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedPlayHistory {
            get {
                return ((string)(this["SavedPlayHistory"]));
            }
            set {
                this["SavedPlayHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedShuffledQueue {
            get {
                return ((string)(this["SavedShuffledQueue"]));
            }
            set {
                this["SavedShuffledQueue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAlbumViewEnabled {
            get {
                return ((bool)(this["IsAlbumViewEnabled"]));
            }
            set {
                this["IsAlbumViewEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full")]
        public string LastTimeDisplayMode {
            get {
                return ((string)(this["LastTimeDisplayMode"]));
            }
            set {
                this["LastTimeDisplayMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AlbumSplitterWidth {
            get {
                return ((double)(this["AlbumSplitterWidth"]));
            }
            set {
                this["AlbumSplitterWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AlbumsListScrollPos {
            get {
                return ((double)(this["AlbumsListScrollPos"]));
            }
            set {
                this["AlbumsListScrollPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedAlbumTitle {
            get {
                return ((string)(this["LastSelectedAlbumTitle"]));
            }
            set {
                this["LastSelectedAlbumTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsShowTenthsEnabled {
            get {
                return ((bool)(this["IsShowTenthsEnabled"]));
            }
            set {
                this["IsShowTenthsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppName")]
        public string WindowTitleMode {
            get {
                return ((string)(this["WindowTitleMode"]));
            }
            set {
                this["WindowTitleMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsMediaKeysEnabled {
            get {
                return ((bool)(this["IsMediaKeysEnabled"]));
            }
            set {
                this["IsMediaKeysEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string SelectedTitleBarColorMode {
            get {
                return ((string)(this["SelectedTitleBarColorMode"]));
            }
            set {
                this["SelectedTitleBarColorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppName")]
        public string SelectedTitleBarTextMode {
            get {
                return ((string)(this["SelectedTitleBarTextMode"]));
            }
            set {
                this["SelectedTitleBarTextMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string SelectedTransitionMode {
            get {
                return ((string)(this["SelectedTransitionMode"]));
            }
            set {
                this["SelectedTransitionMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSkipSilenceEnabled {
            get {
                return ((bool)(this["IsSkipSilenceEnabled"]));
            }
            set {
                this["IsSkipSilenceEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double TransitionDuration {
            get {
                return ((double)(this["TransitionDuration"]));
            }
            set {
                this["TransitionDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSplashScreen {
            get {
                return ((bool)(this["ShowSplashScreen"]));
            }
            set {
                this["ShowSplashScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string BrowserAlternatingStyle {
            get {
                return ((string)(this["BrowserAlternatingStyle"]));
            }
            set {
                this["BrowserAlternatingStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string PlaylistAlternatingStyle {
            get {
                return ((string)(this["PlaylistAlternatingStyle"]));
            }
            set {
                this["PlaylistAlternatingStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsShuffleActive {
            get {
                return ((bool)(this["IsShuffleActive"]));
            }
            set {
                this["IsShuffleActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsHorizontalVolumeEnabled {
            get {
                return ((bool)(this["IsHorizontalVolumeEnabled"]));
            }
            set {
                this["IsHorizontalVolumeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Volume_VU_Waveform")]
        public string BottomPanelLayout {
            get {
                return ((string)(this["BottomPanelLayout"]));
            }
            set {
                this["BottomPanelLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMinimizeToTrayEnabled {
            get {
                return ((bool)(this["IsMinimizeToTrayEnabled"]));
            }
            set {
                this["IsMinimizeToTrayEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMiniPlayerEnabled {
            get {
                return ((bool)(this["IsMiniPlayerEnabled"]));
            }
            set {
                this["IsMiniPlayerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsNowPlayingFluidBackgroundEnabled {
            get {
                return ((bool)(this["IsNowPlayingFluidBackgroundEnabled"]));
            }
            set {
                this["IsNowPlayingFluidBackgroundEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowTop {
            get {
                return ((double)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double WindowLeft {
            get {
                return ((double)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string WindowState {
            get {
                return ((string)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MiniPlayerLeft {
            get {
                return ((double)(this["MiniPlayerLeft"]));
            }
            set {
                this["MiniPlayerLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MiniPlayerTop {
            get {
                return ((double)(this["MiniPlayerTop"]));
            }
            set {
                this["MiniPlayerTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsCleanModeEnabled {
            get {
                return ((bool)(this["IsCleanModeEnabled"]));
            }
            set {
                this["IsCleanModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsOptimizedWindowModeEnabled {
            get {
                return ((bool)(this["IsOptimizedWindowModeEnabled"]));
            }
            set {
                this["IsOptimizedWindowModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Split")]
        public string VuMeterStyle {
            get {
                return ((string)(this["VuMeterStyle"]));
            }
            set {
                this["VuMeterStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AlbumScrollPos {
            get {
                return ((double)(this["AlbumScrollPos"]));
            }
            set {
                this["AlbumScrollPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsNowPlayingFluidAudioReactiveEnabled {
            get {
                return ((bool)(this["IsNowPlayingFluidAudioReactiveEnabled"]));
            }
            set {
                this["IsNowPlayingFluidAudioReactiveEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAutoHideControlsEnabled {
            get {
                return ((bool)(this["IsAutoHideControlsEnabled"]));
            }
            set {
                this["IsAutoHideControlsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SmartAccent")]
        public string ColorExtractionAlgorithm {
            get {
                return ((string)(this["ColorExtractionAlgorithm"]));
            }
            set {
                this["ColorExtractionAlgorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FixedPrimaryColor {
            get {
                return ((string)(this["FixedPrimaryColor"]));
            }
            set {
                this["FixedPrimaryColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSmoothScrollEnabled {
            get {
                return ((bool)(this["IsSmoothScrollEnabled"]));
            }
            set {
                this["IsSmoothScrollEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsTaskbarProgressEnabled {
            get {
                return ((bool)(this["IsTaskbarProgressEnabled"]));
            }
            set {
                this["IsTaskbarProgressEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsMinimalBottomPanelEnabled {
            get {
                return ((bool)(this["IsMinimalBottomPanelEnabled"]));
            }
            set {
                this["IsMinimalBottomPanelEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPlaylistMinimalModeEnabled {
            get {
                return ((bool)(this["IsPlaylistMinimalModeEnabled"]));
            }
            set {
                this["IsPlaylistMinimalModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPlaylistSidebarCollapsed {
            get {
                return ((bool)(this["IsPlaylistSidebarCollapsed"]));
            }
            set {
                this["IsPlaylistSidebarCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAlbumSidebarCollapsed {
            get {
                return ((bool)(this["IsAlbumSidebarCollapsed"]));
            }
            set {
                this["IsAlbumSidebarCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsBrowserSidebarCollapsed {
            get {
                return ((bool)(this["IsBrowserSidebarCollapsed"]));
            }
            set {
                this["IsBrowserSidebarCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Off")]
        public string RepeatMode {
            get {
                return ((string)(this["RepeatMode"]));
            }
            set {
                this["RepeatMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFullscreenF10Enabled {
            get {
                return ((bool)(this["IsFullscreenF10Enabled"]));
            }
            set {
                this["IsFullscreenF10Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGlassModeEnabled {
            get {
                return ((bool)(this["IsGlassModeEnabled"]));
            }
            set {
                this["IsGlassModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClassicFolderScrollJson {
            get {
                return ((string)(this["ClassicFolderScrollJson"]));
            }
            set {
                this["ClassicFolderScrollJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlbumFolderScrollJson {
            get {
                return ((string)(this["AlbumFolderScrollJson"]));
            }
            set {
                this["AlbumFolderScrollJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavedAlbumsTracksScrollJson {
            get {
                return ((string)(this["SavedAlbumsTracksScrollJson"]));
            }
            set {
                this["SavedAlbumsTracksScrollJson"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPlayerLogoHidden {
            get {
                return ((bool)(this["IsPlayerLogoHidden"]));
            }
            set {
                this["IsPlayerLogoHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string BeautifulLyricsFont {
            get {
                return ((string)(this["BeautifulLyricsFont"]));
            }
            set {
                this["BeautifulLyricsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsAlwaysShowTrackTimingsEnabled {
            get {
                return ((bool)(this["IsAlwaysShowTrackTimingsEnabled"]));
            }
            set {
                this["IsAlwaysShowTrackTimingsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int HotkeySkipForwardSeconds {
            get {
                return ((int)(this["HotkeySkipForwardSeconds"]));
            }
            set {
                this["HotkeySkipForwardSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int HotkeySkipBackwardSeconds {
            get {
                return ((int)(this["HotkeySkipBackwardSeconds"]));
            }
            set {
                this["HotkeySkipBackwardSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int HotkeyVolumeUpPercent {
            get {
                return ((int)(this["HotkeyVolumeUpPercent"]));
            }
            set {
                this["HotkeyVolumeUpPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int HotkeyVolumeDownPercent {
            get {
                return ((int)(this["HotkeyVolumeDownPercent"]));
            }
            set {
                this["HotkeyVolumeDownPercent"] = value;
            }
        }
    }
}
